$script = <<"END"
apt install -y apache2 nginx
echo "Listen 8084" > /etc/apache2/ports.conf
rm /etc/apache2/sites-available/*
rm /etc/apache2/sites-enabled/*
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*
mkdir /opt/apache2
mkdir /opt/nginx
echo "Hello World!" > /opt/apache2/test.txt
echo "Hello World!" > /opt/nginx/test.txt
cat <<\EOF > /opt/apache2/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
    </head>
    <body>
        <p>This is an example of a simple HTML page with one paragraph.</p>
    </body>
</html>
EOF
cat <<\EOF > /opt/nginx/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
    </head>
    <body>
        <p>This is an example of a simple HTML page with one paragraph.</p>
    </body>
</html>
EOF
chown -R www-data: /opt/apache2/
chown -R www-data: /opt/nginx/
cat <<\EOF > /etc/apache2/sites-available/mysite.conf
<VirtualHost *:8084>

ServerName mysite
DocumentRoot /opt/apache2/

<Directory /opt/apache2/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

</VirtualHost>
EOF
a2ensite mysite
/etc/init.d/apache2 start
cat <<\EOF > /etc/nginx/conf.d/mysite.conf
server {
        listen 8085 default_server;
        listen [::]:8085 default_server;
        root /opt/nginx;
        index test.html;
        server_name _;
        location / {
                try_files \\$uri \\$uri/ =404;
        }
      }
EOF
/etc/init.d/nginx start
END


Vagrant.configure(2) do |config|
  # Path to ssh key
  config.ssh.private_key_path = "/Users/boriskoltun/.ssh/id_ed25519"

  # VM definition
  config.vm.define "ubuntu", primary: true do |srv|
    srv.vm.hostname = "ubuntu"
    srv.vm.network "forwarded_port", id: "apache", host: 8084, guest: 8084
    srv.vm.network "forwarded_port", id: "nginx", host: 8085, guest: 8085
#    srv.vm.network :private_network, ip: "172.18.0.2"
    srv.vm.provision "shell", inline: $script
  end

  # Custom configuration for docker
  config.vm.provider "docker" do |d, override|
    # docker doesnt use boxes
    override.vm.box = nil

    # this is where your Dockerfile lives
    d.build_dir = "."

    # Make sure it sets up ssh with the Dockerfile
    # Vagrant is pretty dependent on ssh
    override.ssh.insert_key = true
    d.has_ssh = true

    # Configure Docker to allow access to more resources
    d.privileged = true
  end

# ...

end
